# Generated by Django 4.2.7 on 2023-11-08 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Table1',
        ),
    ]
